name: Test

# Event triggers
on:
  workflow_dispatch:
  pull_request:
    branches: [master, main]
    types:
      - opened
      - reopened
      - review_requested
      - edited
  push:
    branches: [main, master]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: echo "install dependencies"

  zip:
    name: Create zip file
    runs-on: ubuntu-latest
    steps:
      - run: |
            pwd
            touch test.txt
            ls -ltr
            zip -r ${{github.sha}}.zip .

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with: 
          name: zipped-bundle
          path: ${{github.sha}}.zip
  
  publish:
    name: Publish artifact
    runs-on: ubuntu-latest
    needs: [zip]
    steps:
      - name: create release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{secrets.github_token}}
        with:
          tag_name: ${{github.run_number}}
          release_name: Release from ${{github.run_number}}
          body: New release from ${{github.sha}}. Release notes can be found on the documentation site
          draft: false
          prerelease: false


  test:
    name: Test image
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Unit Testing
        run: echo "Unit Testing"
  
  deploy:
    name: Deploy artifact
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Retrieve artifact
        run: echo "Download artifact"
      - name: Deploy artifact"
        run: echo "Deploy artifact"

