name: Run Unit Test

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  get_code:
    name: Get code from repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  set_up:
    name: Set up Java
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
  
  test:
    name: Exceute Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew test
    
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up JDK 11
  #       uses: actions/setup-java@v2
  #       with:
  #         java-version: '17'
  #         distribution: 'adopt'
  #         cache: gradle
  #     - name: Grant execute permission for gradlew
  #       run: chmod +x gradlew
  #     - name: Build with Gradle
  #       run: ./gradlew build