name: Run Unit Test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    

jobs:
  test:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Display content of folder
        run: |
            pwd 
            ls -ltr

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test