name: Run unit tests

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        run: |
            echo "Download code"
      - name: test
        run: |
            echo "gradlew test"

  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: zipped-bundle

  display_path_content:
    runs-on: ubuntu-latest
    steps:
      - name: PWD
        run: pwd
