name: Run unit tests

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        run: |
            echo "Download code"
      - name: test
        run: |
            echo "gradlew test"