name: Run unit tests - Reusable

on:
  workflow_call:
    inputs:
      version_number: 
        description: version of artifact
        required: true
        default: 1.0.0
        type: string
    
  push:
    branches-ignore:
      - main
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        run: |
            echo "Download code"
            echo "Version"
            echo ${{ inputs.version_number }}
  
  version_1_validation:
    if: ${{ startsWith(inputs.version_number, '1.') }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: version 1.x
        run: echo "Version 1.x.x"
      - name: version 1.1.x
        if: ${{ startsWith(inputs.version_number, '1.1') }}
        run: echo "Version 1.1.x"
      - name: version 1.0.x
        if: ${{ startsWith(inputs.version_number, '1.0') }}
        run: echo "Version 1.0.x"

  version_2_validation:
    if: ${{ startsWith(inputs.version_number, '2.') }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: version 2.x
        run: echo "Version 2.x.x"

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: test
        run: |
            echo "gradlew test"

  postgres_container:
    runs-on: ubuntu-latest
    services:
      postgres: 
        image: postgres
        env:
          POSTGRES_USER: session_user
          POSTGRES_PASSWORD: session_user
          POSTGRES_DB: sessiondb
        # volumes:
        #   - "pingfed-databases/bmj-session-database/bmj-session-database/sql:/docker-entrypoint-initdb.d/"
        # ports:
        #   - 5432:5432
    steps:
      - name: Connect to PostgreSQL "pingfed-databases/bmj-session-database/bmj-session-database/sql:/docker-entrypoint-initdb.d/"
        run: |
            sudo apt-get install postgresql-client
            psql --version
            psql -h localhost -p session_user -U session_user -d sessiondb

  # example-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download a single artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: zipped-bundle

  display_path_content:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: PWD
        run: pwd
